version: '2'
services:
  web:
    build: .
    volumes:
     - .:/app
    ports:
     - "8000:8000"
    depends_on:
       - postgres
       - redis
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    build: .
    volumes:
     - .:/app
    depends_on:
       - postgres
       - redis
    command: celery --app=ciupy3 worker --loglevel=info --queues=high,default --beat


  postgres:
     image: postgres
     volumes:
      - postgres-data:/var/lib/postgresql/data

  # :alpine uses Alpine Linux project and leads to much smaller image size
  redis:
    image: "redis:alpine"

volumes:
  postgres-data:
