---
pipelining: true
redis_syslog_enabled: "no"
redis_max_memory: 128mb
apt_cache_valid_time: 86400
apt_install_packages: yes
apt_upgrade: "safe"

unattended_allowed_origins: [security, updates]
unattended_automatic_reboot: true
unattended_mail: 'jannis+caniusepython3@leidel.info'

deploy_user: ciupy3
deploy_app_name: "{{deploy_user}}"
deploy_dir: "/home/{{deploy_app_name}}"
deploy_env: prod

postgresql_ext_install_contrib: yes
postgresql_ext_install_dev_headers: no
postgresql_ext_install_postgis: no
postgresql_databases:
  - name: "{{deploy_user}}"
    hstore: yes         # flag to install the hstore extension on this database (yes/no)
    uuid-ossp: yes      # flag to install the uuid-ossp extension on this database (yes/no)

postgresql_users:
  - name: "{{deploy_user}}"
    pass: "{{deploy_user}}"

postgresql_user_privileges:
  - name: "{{deploy_user}}"
    db: "{{deploy_user}}"
    priv: "ALL"

timezone_zone: UTC

source_user: "{{deploy_user}}"
source_sources:
  - repo: https://github.com/jezdez/caniusepython3.com.git
    dest: "{{deploy_src_dir}}"
source_reload_cmd: "restart {{deploy_user}}-uwsgi"

wsgi_app: "{{wsgi_src_dir}}/{{deploy_user}}/wsgi.py"
wsgi_deb_packages:
  - python-dev
  - python-pip
  - python-virtualenv
  - libjpeg-dev
  - postgresql-server-dev-all
  - bsd-mailx
wsgi_env_python: python
wsgi_nginx_static_locations: []
wsgi_nginx_port: 443 ssl
wsgi_nginx_options:
  - ssl_certificate {{ciupy3_ssl_crt_path}};
  - ssl_certificate_key {{ciupy3_ssl_key_path}};
  - ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
  - ssl_ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;      ssl_prefer_server_ciphers on;
  - ssl_session_cache shared:SSL:10m;
  - ssl_session_timeout 10m;
wsgi_uwsgi_enable_threads: yes

nginx_delete_default_site: yes
nginx_servers:
  -
    - listen 80 default_server;
    - server_name {{wsgi_nginx_servernames.split(' ')[0]}};
    - return 301 https://$server_name$request_uri;
  -
    - listen 80;
    - server_name flower.{{wsgi_nginx_servernames.split(' ')[0]}};
    - charset utf-8;
    - "location / {"
    -     proxy_pass http://127.0.0.1:5555;
    -     proxy_set_header Host $host;
    -     proxy_redirect off;
    -     proxy_http_version 1.1;
    -     proxy_set_header Upgrade $http_upgrade;
    -     proxy_set_header Connection "upgrade";
    - "}"

django_settings_module: "ciupy3.settings.local"
django_settings_databases:
  - default:
      ENGINE: django.db.backends.postgresql_psycopg2
      NAME: "{{ postgresql_databases.0.name }}"
      USER: "{{ postgresql_users.0.name }}"
      PASSWORD: "{{ postgresql_users.0.pass }}"

celery_bin: "{{wsgi_env_dir}}/bin/celery"
celery_run:
- { action: worker, queue: 'high,default' }
- { action: beat }
- { action: flower }
