---

celery_enabled: yes                                   # The role is enabled
celery_remove: no                                     # Uninstall the role

celery_app_name: "{{deploy_app_name|default('web')}}" # Application name
celery_bin: celery                                    # Celery executable. Ex:
                                                      # celery_bin: /path/to/virtualenv/bin/celery
                                                      # celery_bin: "python /path/to/django/manage.py celery --settings=settings"
                                                      # celery_bin: "/path/to/virtualenv/python /path/to/django/manage.py celery --settings=settings"
                  

celery_run:                                           # Start celery. See default values below. Ex:
- { action: worker }                                  # - { action: worker, queue: 'hard', concurrency: 4, loglevel: debug, user=deploy }
- { action: beat }                                    # - { action: beat, loglevel: debug }
                                                      # - { action: worker, opts: '--settings=settings.local' }

celery_concurrency: 1                                 # Set default concurence level
celery_user: "{{deploy_user|default('root')}}"        # Set default user
celery_group: "{{deploy_group|default('root')}}"      # Set default group
celery_app_dir: "{{deploy_src_dir|default('/usr/lib/' + celery_app_name)}}" # Set default application directory
celery_app_module: "{{celery_app_name}}"              # Set default application module
celery_run_dir: "{{deploy_run_dir|default(celery_app_dir + '/run')}}" # Set default run directory
celery_log_dir: "{{deploy_log_dir|default(celery_app_dir + '/log')}}" # Set default log directory
celery_log_level: info                                # Set default log level
celery_log_rotate: yes                                # Enable log rotation
celery_opts:                                          # Set additional options

# vim:sw=2:ft=ansible
